<?php

declare(strict_types=1);

namespace Semitexa\Theme\Skin;

final class TokenEmitter
{
    public function emit(SkinPalette $palette, string $selector = ':root'): string
    {
        $lines = ['/* Generated by semitexa/theme — do not edit manually. */'];
        $lines[] = "{$selector} {";
        foreach ($palette->tokens as $var => $hex) {
            $lines[] = "    {$var}: {$hex};";
        }
        $lines[] = '}';
        $lines[] = '';
        return implode("\n", $lines);
    }
}
