<?php

declare(strict_types=1);

namespace Semitexa\Theme\Application\Service\Skin;

/**
 * Emits the canonical skin tokens.css from a dual-mode palette.
 *
 * The output layout is fixed (see TokenSchema): file header → :root with
 * `color-scheme: light dark` → section dividers in canonical order →
 * tokens via `light-dark(L, D)` (or single value if mode-invariant) →
 * data-skin-mode pinning blocks. Ordering is fully deterministic; running
 * the emitter twice on the same palette + context produces byte-identical
 * output.
 *
 * Every `tokens.css` in `src/skins/*` is produced by this single emitter —
 * algorithm-generated, manual, or LLM-prompted skins all flow through here.
 */
final class TokenEmitter
{
    /** Trailing characters used between `--ui-...` and its `:` for column alignment. */
    private const NAME_PADDING = 4;

    public function emit(DualSkinPalette $palette, EmitterContext $ctx): string
    {
        TokenSchema::assertCoversTokenContract();

        $invariant = array_flip($palette->modeInvariantTokens());
        $lines = $this->header($ctx);

        $lines[] = ':root {';
        $lines[] = '    color-scheme: light dark;';

        foreach (TokenSchema::sections() as $section) {
            $tokens = TokenSchema::tokensInSection($section);
            $width = $this->columnWidth($tokens);

            $lines[] = '';
            $lines[] = '    /* ' . $section . ' — ' . TokenSchema::sectionDescription($section) . ' */';

            foreach ($tokens as $name) {
                $lightValue = $palette->light[$name];
                $darkValue  = $palette->dark[$name];
                $isInvariant = isset($invariant[$name]);
                $value = $isInvariant
                    ? $lightValue
                    : sprintf('light-dark(%s, %s)', $lightValue, $darkValue);
                $padding = str_repeat(' ', $width - strlen($name));
                $lines[] = sprintf('    %s:%s %s;', $name, $padding, $value);
            }
        }

        $lines[] = '}';
        $lines[] = '';
        $lines[] = ':root[data-skin-mode="light"] { color-scheme: light; }';
        $lines[] = ':root[data-skin-mode="dark"]  { color-scheme: dark; }';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * @return list<string>
     */
    private function header(EmitterContext $ctx): array
    {
        $description = $ctx->description !== null && $ctx->description !== ''
            ? ' — ' . rtrim($ctx->description, '.')
            : '';
        $seed = $ctx->seedHex !== null && $ctx->seedHex !== '' ? $ctx->seedHex : 'n/a';
        return [
            "/* Skin: {$ctx->name}{$description}.",
            " * algorithm={$ctx->algorithm}  source={$ctx->source}  seed={$seed}  generated={$ctx->generatedAt}.",
            ' * Generated by semitexa/theme — do not edit manually.',
            " * Regenerate via `bin/semitexa skins:rebuild {$ctx->name}`.",
            ' */',
        ];
    }

    /**
     * @param list<string> $tokens
     */
    private function columnWidth(array $tokens): int
    {
        $max = 0;
        foreach ($tokens as $name) {
            $len = strlen($name);
            if ($len > $max) {
                $max = $len;
            }
        }
        return $max + self::NAME_PADDING;
    }
}
